[package]
name = "snarkvm-console-program"
version = "0.11.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[features]
default = [ ]
test = [ ]

[dependencies.snarkvm-console-account]
path = "../account"
version = "0.11.1"

[dependencies.snarkvm-console-collections]
path = "../collections"
version = "0.11.1"

[dependencies.snarkvm-console-network]
path = "../network"
version = "0.11.1"

[dependencies.snarkvm-console-types]
path = "../types"
version = "0.11.1"

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.11.1"

[dependencies.enum_index]
version = "0.2"

[dependencies.enum_index_derive]
version = "0.2"

[dependencies.indexmap]
version = "1.9"

[dependencies.num-derive]
version = "0.3"

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.17.1"

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.bincode]
version = "1.3"
