[package]
name = "snarkvm-console-program"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-account]
path = "../account"
version = "0.7.5"

[dependencies.snarkvm-console-network]
path = "../network"
version = "0.7.5"

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"

[dependencies.anyhow]
version = "1.0.58"

[dependencies.enum_index]
version = "0.2"

[dependencies.enum_index_derive]
version = "0.2"

[dependencies.itertools]
version = "0.10.1"

[dependencies.once_cell]
version = "1.12.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.rand]
version = "0.8"

[dev-dependencies.serde_json]
version = "1.0"
