[package]
name = "snarkvm-circuit-account"
version = "0.11.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account circuit library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-account"
path = "../../console/account"
version = "0.11.1"
optional = true

[dependencies.snarkvm-circuit-algorithms]
path = "../algorithms"
version = "0.11.1"

[dependencies.snarkvm-circuit-network]
path = "../network"
version = "0.11.1"

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "0.11.1"

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"

[dev-dependencies.anyhow]
version = "1.0.71"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
