[package]
name = "snarkvm-circuit-environment"
version = "0.13.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Circuit environment for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[[bench]]
name = "linear_combination"
path = "benches/linear_combination.rs"
harness = false

[dependencies.console]
package = "snarkvm-console-network"
path = "../../console/network"
version = "=0.13.0"

[dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "=0.13.0"
default-features = false
features = [ "r1cs" ]

[dependencies.snarkvm-circuit-environment-witness]
path = "./witness"
version = "=0.13.0"
default-features = false

[dependencies.snarkvm-curves]
path = "../../curves"
version = "=0.13.0"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "=0.13.0"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "=0.13.0"
default-features = false

[dependencies.indexmap]
version = "2.0.0"

[dependencies.itertools]
version = "0.11.0"

[dependencies.nom]
version = "7.1"

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.18.0"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
features = [ "polycommit_full", "snark" ]

[dev-dependencies.snarkvm-circuit]
path = "../../circuit"

[dev-dependencies.snarkvm-console-types]
path = "../../console/types"

[dev-dependencies.criterion]
version = "0.5"

[features]
default = [ "snarkvm-curves/default" ]
