[package]
name = "snarkvm-r1cs"
version = "0.11.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "R1CS for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[dependencies.snarkvm-curves]
path = "../curves"
version = "=0.11.4"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "=0.11.4"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "=0.11.4"

[dependencies.anyhow]
version = "1.0.71"

[dependencies.cfg-if]
version = "1.0.0"

[dependencies.fxhash]
version = "0.2.1"

[dependencies.indexmap]
version = "1.9.3"

[dependencies.itertools]
version = "0.10.3"

[dependencies.thiserror]
version = "1.0"

[features]
default = [ ]
