[package]
name = "snarkvm-r1cs"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "R1CS for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.7.5"

[dependencies.anyhow]
version = "1.0.51"

[dependencies.cfg-if]
version = "1.0.0"

[dependencies.fxhash]
version = "0.2.1"

[dependencies.indexmap]
version = "1.7.0"

[dependencies.itertools]
version = "0.10.1"

[dependencies.thiserror]
version = "1.0"

[features]
default = [ ]
