[package]
name = "snarkvm"
version = "0.2.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "snarkvm", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
  "algorithms",
  "curves",
  "derives",
  "dpc",
  "fields",
  "gadgets",
  "marlin",
  "objects",
  "parameters",
  "polycommit",
  "posw",
  "profiler",
  "r1cs",
  "storage",
  "testing",
  "utilities",
  "wasm"
]

[[bin]]
name = "snarkvm"
path = "snarkvm/main.rs"

[dependencies.anyhow]
version = "1.0.38"

[dependencies.colored]
version = "2"

[dependencies.self_update]
version = "0.25"

[dependencies.structopt]
version = "0.3"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
