[package]
name = "snarkvm"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "snarkvm", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
  "algorithms",
  "curves",
  "derives", # excluded from [features], for internal use primarily
  "dpc",
  "fields",
  "gadgets",
  "marlin", # excluded from [features], to be merged in `algorithms` and `gadgets` once stable
  "parameters",
  "polycommit", # excluded from [features], to be merged in `algorithms` and `gadgets` once stable
  "profiler", # excluded from [features], for internal use primarily
  "r1cs",
  "utilities",
  "wasm", # excluded from [features], WASM contexts will typically import this crate directly
  ".integration" # excluded from [features], for CI only
]

[lib]
path = "snarkvm/lib.rs"

[[bin]]
name = "snarkvm"
path = "snarkvm/cli/main.rs"
required-features = ["cli"]

[features]
default = ["core"]
#
# `core` is defined as the commonly-used members of snarkVM with default features.
#
# If you need more granular control of members and/or member features,
# please import the requisite crates directly and enable features as needed.
core = ["dpc", "utilities"]
full = ["algorithms", "curves", "dpc", "fields", "gadgets", "parameters", "r1cs", "utilities"]

## snarkVM workspace ##
algorithms = ["snarkvm-algorithms"]
curves = ["snarkvm-curves"]
dpc = ["snarkvm-dpc"]
fields = ["snarkvm-fields"]
gadgets = ["snarkvm-gadgets"]
parameters = ["snarkvm-parameters"]
r1cs = ["snarkvm-r1cs"]
utilities = ["snarkvm-utilities"]

## snarkVM workspace specific ##
parameters_no_std_out = ["snarkvm-parameters/no_std_out"]

## snarkVM CLI ##
cli = ["anyhow", "colored", "self_update", "structopt", "thiserror"]

## CI ##
noconfig = []

[dependencies.snarkvm-algorithms]
path = "./algorithms"
version = "0.7.5"
optional = true

[dependencies.snarkvm-curves]
path = "./curves"
version = "0.7.5"
optional = true

[dependencies.snarkvm-dpc]
path = "./dpc"
version = "0.7.5"
optional = true

[dependencies.snarkvm-fields]
path = "./fields"
version = "0.7.5"
optional = true

[dependencies.snarkvm-gadgets]
path = "./gadgets"
version = "0.7.5"
optional = true

[dependencies.snarkvm-parameters]
path = "./parameters"
version = "0.7.5"
optional = true

[dependencies.snarkvm-r1cs]
path = "./r1cs"
version = "0.7.5"
optional = true

[dependencies.snarkvm-utilities]
path = "./utilities"
version = "0.7.5"
optional = true

[dependencies.anyhow]
version = "1.0.44"
optional = true

[dependencies.colored]
version = "2"
optional = true

[dependencies.self_update]
version = "0.27"
optional = true

[dependencies.structopt]
version = "0.3"
optional = true

[dependencies.thiserror]
version = "1.0"
optional = true

[dev-dependencies.rusty-hook]
version = "0.11.2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
