[package]
name = "snarkvm-console-account"
version = "0.14.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account operations for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies.snarkvm-console-network]
path = "../network"
version = "=0.14.6"

[dependencies.snarkvm-console-types]
path = "../types"
version = "=0.14.6"
default-features = false
features = [ "address", "field", "group", "scalar" ]

[dependencies.bs58]
version = "0.5"

[dependencies.ed25519-dalek]
version = "1.0"
optional = true

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.criterion]
version = "0.5.1"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[features]
default = [
  "compute_key",
  "graph_key",
  "private_key",
  "signature",
  "view_key"
]
compute_key = [ "private_key" ]
graph_key = [ "private_key" ]
private_key = [ "compute_key" ]
signature = [ "compute_key" ]
view_key = [ ]
ed25519 = [ "ed25519-dalek" ]
