[package]
name = "snarkvm-compiler"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "0.9.0"
default-features = false

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-parameters]
path = "../../parameters"
version = "0.9.0"
optional = true

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.9.0"
default-features = false

[dependencies.anyhow]
version = "1.0.64"

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "1.8"
features = [ "serde", "rayon" ]

[dependencies.once_cell]
version = "1.13"

[dependencies.parking_lot]
version = "0.12"

[dependencies.paste]
version = "1.0.9"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"
optional = true

[dependencies.serde]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.time]
version = "0.3.15"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.regex]
version = "1.6"

[dev-dependencies.tracing-test]
version = "0.2"

[features]
default = [
  "parallel",
  "snarkvm-algorithms/default",
  "circuit/default",
  "console/default",
  "snarkvm-curves/default",
  "snarkvm-fields/default",
  "snarkvm-parameters/default"
]
parallel = [
  "rayon",
  "snarkvm-fields/parallel",
  "snarkvm-utilities/parallel",
  "snarkvm-parameters/default"
]
aleo-cli = [ "snarkvm-parameters/default" ]
enclave = [
  "snarkvm-algorithms/enclave",
  "circuit/enclave",
  "console/enclave",
  "snarkvm-curves/enclave",
  "snarkvm-fields/enclave",
  "snarkvm-utilities/enclave"
]
