[package]
name = "snarkvm-ledger-store"
version = "0.14.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A data store for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "web-programming" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "indexmap/rayon", "rayon" ]
rocks = [ "aleo-std", "once_cell", "rocksdb", "tracing" ]
serial = [
  "console/serial",
  "ledger-block/serial",
  "ledger-coinbase/serial",
  "synthesizer-program/serial",
  "synthesizer-snark/serial"
]

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.14.6"

[dependencies.ledger-authority]
package = "snarkvm-ledger-authority"
path = "../authority"
version = "=0.14.6"

[dependencies.ledger-block]
package = "snarkvm-ledger-block"
path = "../block"
version = "=0.14.6"

[dependencies.ledger-coinbase]
package = "snarkvm-ledger-coinbase"
path = "../coinbase"
version = "=0.14.6"

[dependencies.synthesizer-program]
package = "snarkvm-synthesizer-program"
path = "../../synthesizer/program"
version = "=0.14.6"

[dependencies.synthesizer-snark]
package = "snarkvm-synthesizer-snark"
path = "../../synthesizer/snark"
version = "=0.14.6"

[dependencies.aleo-std]
version = "0.1.18"
default-features = false
optional = true

[dependencies.anyhow]
version = "1.0.72"

[dependencies.bincode]
version = "1.3"

[dependencies.indexmap]
version = "2.0"
features = [ "serde" ]

[dependencies.once_cell]
version = "1.18"
optional = true

[dependencies.parking_lot]
version = "0.12"

[dependencies.rayon]
version = "1"
optional = true

[dependencies.rocksdb]
version = "0.21"
default-features = false
features = [ "lz4" ]
optional = true

[dependencies.serde]
version = "1.0"

[dependencies.tracing]
version = "0.1"
optional = true

[dev-dependencies.ledger-test-helpers]
package = "snarkvm-ledger-test-helpers"
path = "../../ledger/test-helpers"

[dev-dependencies.serial_test]
version = "2"

[dev-dependencies.tempfile]
version = "3.7"

[dev-dependencies.tracing-test]
version = "0.2"
