[package]
name = "snarkvm-synthesizer-process"
version = "0.16.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A process for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "indexmap/rayon", "rayon" ]
aleo-cli = [ ]
async = [ "ledger-query/async" ]
rocks = [ "ledger-store/rocks" ]
serial = [
  "console/serial",
  "ledger-block/serial",
  "ledger-query/serial",
  "ledger-store/serial",
  "synthesizer-program/serial",
  "synthesizer-snark/serial"
]
wasm = [
  "console/wasm",
  "ledger-block/wasm",
  "ledger-query/wasm",
  "synthesizer-program/wasm",
  "synthesizer-snark/wasm"
]
timer = [ "aleo-std/timer" ]

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.16.1"
default-features = false
features = [ "network", "program", "types" ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "=0.16.1"

[dependencies.ledger-block]
package = "snarkvm-ledger-block"
path = "../../ledger/block"
version = "=0.16.1"

[dependencies.ledger-query]
package = "snarkvm-ledger-query"
path = "../../ledger/query"
version = "=0.16.1"
default-features = false

[dependencies.ledger-store]
package = "snarkvm-ledger-store"
path = "../../ledger/store"
version = "=0.16.1"

[dependencies.synthesizer-program]
package = "snarkvm-synthesizer-program"
path = "../../synthesizer/program"
version = "=0.16.1"

[dependencies.synthesizer-snark]
package = "snarkvm-synthesizer-snark"
path = "../../synthesizer/snark"
version = "=0.16.1"

[dependencies.aleo-std]
version = "0.1.18"
default-features = false

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "2.0"
features = [ "serde" ]

[dependencies.once_cell]
version = "1.18"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"
optional = true

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.ledger-committee]
package = "snarkvm-ledger-committee"
path = "../../ledger/committee"
default-features = false

[dev-dependencies.ledger-query]
package = "snarkvm-ledger-query"
path = "../../ledger/query"
default-features = false
features = [ "query" ]

[dev-dependencies.ledger-store]
package = "snarkvm-ledger-store"
path = "../../ledger/store"
features = [ "test" ]

[dev-dependencies.ledger-test-helpers]
package = "snarkvm-ledger-test-helpers"
path = "../../ledger/test-helpers"

[dev-dependencies.tempfile]
version = "3"
