[package]
name = "snarkvm-posw"
version = "0.4.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Proof of Succinct Work circuit implementation based on [KB20]"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[[bench]]
name = "posw"
path = "benches/posw.rs"
harness = false

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-dpc]
path = "../dpc"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-gadgets]
path = "../gadgets"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-marlin]
path = "../marlin"
version = "0.4.0"

[dependencies.snarkvm-parameters]
path = "../parameters"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-polycommit]
path = "../polycommit"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../r1cs"
version = "0.4.0"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.4.0"
default-features = false

[dependencies.blake2]
version = "0.9"
default-features = false

[dependencies.thiserror]
version = "1.0"

[dependencies.rand]
version = "0.8"

[dev-dependencies.criterion]
version = "0.3.4"

[dev-dependencies.hex]
version = "0.4"

[dev-dependencies.rand_xorshift]
version = "0.3.0"
default-features = false

[dev-dependencies.serde]
version = "1.0"

[features]
default = [ "snarkvm-parameters/remote" ]
print-trace = [ "snarkvm-profiler/print-trace" ]
test-helpers = [ ]
