[package]
name = "snarkvm-polycommit"
version = "0.0.4"
authors = [
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "Mary Maller <mary.maller.15@ucl.ac.uk>",
  "Yuncong Hu <huyuncongh@gmail.com>",
  "William Lin",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Noah Vesely <noah.vesely.18@ucl.ac.uk>",
  "Nicholas Ward <npward@berkeley.edu>",
  "The Aleo Team <hello@aleo.org>"
]
description = "A library for constructing polynomial commitment schemes for use in zkSNARKs"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [
  "Cargo.toml",
  "src",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT"
]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.0.4"

[dependencies.snarkvm-errors]
path = "../errors"
version = "0.0.4"

[dependencies.snarkvm-models]
path = "../models"
version = "0.0.4"

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.0.4"

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.0.4"

[dependencies.derivative]
version = "2"
features = [ "use_core" ]

[dependencies.digest]
version = "0.9"

[dependencies.rand_core]
version = "0.6"
default-features = false

[dependencies.rayon]
version = "1"
optional = true

[dev-dependencies.snarkvm-curves]
path = "../curves"

[dev-dependencies.blake2]
version = "0.9"
default-features = false

[dev-dependencies.rand]
version = "0.8"
default-features = false

[features]
default = [ "std" ]
std = [ ]
