[package]
name = "snarkvm-ledger-block"
version = "0.14.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A block for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "web-programming" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "indexmap/rayon", "rayon" ]
serial = [
  "console/serial",
  "ledger-coinbase/serial",
  "synthesizer-program/serial",
  "synthesizer-snark/serial"
]
wasm = [
  "console/wasm",
  "ledger-coinbase/wasm",
  "synthesizer-program/wasm",
  "synthesizer-snark/wasm"
]

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.14.0"

[dependencies.ledger-coinbase]
package = "snarkvm-ledger-coinbase"
path = "../../ledger/coinbase"
version = "=0.14.0"

[dependencies.synthesizer-program]
package = "snarkvm-synthesizer-program"
path = "../../synthesizer/program"
version = "=0.14.0"

[dependencies.synthesizer-snark]
package = "snarkvm-synthesizer-snark"
path = "../../synthesizer/snark"
version = "=0.14.0"

[dependencies.indexmap]
version = "2.0"
features = [ "serde" ]

[dependencies.rayon]
version = "1"
optional = true

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"

[dev-dependencies.ledger-query]
package = "snarkvm-ledger-query"
path = "../query"
default-features = false
features = [ "query" ]

[dev-dependencies.ledger-store]
package = "snarkvm-ledger-store"
path = "../store"

[dev-dependencies.synthesizer-process]
package = "snarkvm-synthesizer-process"
path = "../../synthesizer/process"

[dev-dependencies.once_cell]
version = "1.18"
