[package]
name = "snarkvm-ledger-narwhal-subdag"
version = "0.16.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A subdag for a Narwhal-style memory pool in a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "indexmap/rayon", "rayon" ]
serial = [ "console/serial" ]
wasm = [ "console/wasm" ]
test-helpers = [ "narwhal-batch-certificate/test-helpers" ]

[dependencies.console]
package = "snarkvm-console"
path = "../../../console"
version = "=0.16.1"

[dependencies.narwhal-batch-certificate]
package = "snarkvm-ledger-narwhal-batch-certificate"
path = "../batch-certificate"
version = "=0.16.1"

[dependencies.narwhal-transmission-id]
package = "snarkvm-ledger-narwhal-transmission-id"
path = "../transmission-id"
version = "=0.16.1"

[dependencies.indexmap]
version = "2.0"
features = [ "serde" ]

[dependencies.rayon]
version = "1"
optional = true

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.snarkvm-ledger-narwhal-subdag]
path = "."
features = [ "test-helpers" ]
