[package]
name = "snarkvm-console-collections"
version = "0.14.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Collections for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[[bench]]
name = "merkle_tree"
path = "benches/merkle_tree.rs"
harness = false

[dependencies.snarkvm-console-algorithms]
path = "../algorithms"
version = "=0.14.6"

[dependencies.snarkvm-console-types]
path = "../types"
version = "=0.14.6"
default-features = false
features = [ "field", "integers" ]

[dependencies.aleo-std]
version = "0.1.18"
default-features = false

[dependencies.rayon]
version = "1"

[dev-dependencies.snarkvm-console-network]
path = "../network"

[dev-dependencies.criterion]
version = "0.5.1"

[dev-dependencies.indexmap]
version = "2.0.0"

[features]
serial = [ ]
timer = [ "aleo-std/timer" ]
