[package]
name = "snarkvm"
version = "0.0.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "snarkvm", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[[bin]]
name = "snarkvm"
path = "main.rs"

[dependencies.anyhow]
version = "1.0.38"

[dependencies.colored]
version = "2"

[dependencies.self_update]
version = "0.25"

[dependencies.structopt]
version = "0.3"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.rusty-hook]
version = "0.11.2"
