[package]
name = "snarkvm-wasm"
version = "0.13.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "WASM for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies.snarkvm-console]
path = "../console"
version = "=0.13.0"
features = [ "wasm" ]
optional = true

[dependencies.snarkvm-curves]
path = "../curves"
version = "=0.13.0"
optional = true

[dependencies.snarkvm-fields]
path = "../fields"
version = "=0.13.0"
optional = true

[dependencies.snarkvm-synthesizer]
path = "../synthesizer"
version = "=0.13.0"
features = [ "wasm" ]
optional = true
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "=0.13.0"
optional = true

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.serde]
version = "1.0.164"
default-features = false
features = [ "derive" ]

[dependencies.wasm-bindgen]
version = "0.2"
features = [ "serde-serialize" ]

[dependencies.getrandom]
version = "0.2"
features = [ "js" ]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.37"

[features]
default = [ "full" ]
full = [ "console", "curves", "fields", "synthesizer", "utilities" ]
console = [ "snarkvm-console" ]
curves = [ "snarkvm-curves" ]
fields = [ "snarkvm-fields" ]
synthesizer = [ "snarkvm-synthesizer" ]
utilities = [ "snarkvm-utilities" ]
