[package]
name = "snarkvm-wasm"
version = "0.16.18"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "WASM for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
default = [ "full" ]
full = [
  "circuit",
  "console",
  "curves",
  "fields",
  "ledger",
  "synthesizer",
  "utilities"
]
circuit = [ "snarkvm-circuit-network" ]
console = [ "snarkvm-console" ]
curves = [ "snarkvm-curves" ]
fields = [ "snarkvm-fields" ]
ledger = [
  "snarkvm-ledger-block",
  "snarkvm-ledger-query",
  "snarkvm-ledger-store"
]
synthesizer = [ "snarkvm-synthesizer" ]
utilities = [ "snarkvm-utilities" ]

[dependencies.snarkvm-circuit-network]
path = "../circuit/network"
version = "=0.16.18"
features = [ "wasm" ]
optional = true

[dependencies.snarkvm-console]
path = "../console"
version = "=0.16.18"
features = [ "wasm" ]
optional = true

[dependencies.snarkvm-curves]
path = "../curves"
version = "=0.16.18"
optional = true

[dependencies.snarkvm-fields]
path = "../fields"
version = "=0.16.18"
optional = true

[dependencies.snarkvm-ledger-block]
path = "../ledger/block"
version = "=0.16.18"
features = [ "wasm" ]
optional = true

[dependencies.snarkvm-ledger-query]
path = "../ledger/query"
version = "=0.16.18"
features = [ "async", "wasm" ]
optional = true

[dependencies.snarkvm-ledger-store]
path = "../ledger/store"
version = "=0.16.18"
features = [ "wasm" ]
optional = true

[dependencies.snarkvm-synthesizer]
path = "../synthesizer"
version = "=0.16.18"
default-features = false
features = [ "async", "wasm" ]
optional = true

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "=0.16.18"
features = [ "wasm" ]
optional = true

[dependencies.getrandom]
version = "0.2"
features = [ "js" ]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.37"
