[package]
name = "snarkvm-wasm"
version = "0.7.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "WASM for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.7.4"
optional = true
default-features = false
features = [ "wasm", "parallel" ]

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.7.4"
optional = true
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.7.4"
optional = true
default-features = false

[dependencies.snarkvm-gadgets]
path = "../gadgets"
version = "0.7.4"
optional = true
default-features = false

[dependencies.snarkvm-polycommit]
path = "../polycommit"
version = "0.7.4"
optional = true
default-features = false

[dependencies.snarkvm-r1cs]
path = "../r1cs"
version = "0.7.4"
optional = true
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.7.4"

[dependencies.derivative]
version = "2"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.rand_xorshift]
version = "0.3"
default-features = false

[dependencies.serde]
version = "1.0.125"
default-features = false
features = [ "derive" ]

[dependencies.wasm-bindgen]
version = "0.2"
features = [ "serde-serialize" ]

[dependencies.getrandom]
version = "0.2"
features = [ "js" ]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.24"

[features]
default = [ "full" ]
full = [
  "algorithms",
  "curves",
  "fields",
  "gadgets",
  "polycommit",
  "r1cs"
]
algorithms = [ "snarkvm-algorithms" ]
curves = [ "snarkvm-curves" ]
fields = [ "snarkvm-fields" ]
gadgets = [ "snarkvm-gadgets" ]
polycommit = [ "snarkvm-polycommit" ]
r1cs = [ "snarkvm-r1cs" ]
