[package]
name = "snarkvm-console-types"
version = "0.14.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Console types for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.snarkvm-console-network-environment]
path = "../network/environment"
version = "=0.14.6"

[dependencies.snarkvm-console-types-address]
path = "./address"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-boolean]
path = "./boolean"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-field]
path = "./field"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-group]
path = "./group"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-integers]
path = "./integers"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-scalar]
path = "./scalar"
version = "=0.14.6"
optional = true

[dependencies.snarkvm-console-types-string]
path = "./string"
version = "=0.14.6"
optional = true

[features]
default = [
  "address",
  "boolean",
  "field",
  "group",
  "integers",
  "scalar",
  "string"
]
address = [
  "snarkvm-console-types-address",
  "snarkvm-console-types-field",
  "snarkvm-console-types-group"
]
boolean = [ "snarkvm-console-types-boolean" ]
field = [ "snarkvm-console-types-field" ]
group = [
  "snarkvm-console-types-group",
  "snarkvm-console-types-field",
  "snarkvm-console-types-scalar"
]
integers = [ "snarkvm-console-types-integers" ]
scalar = [
  "snarkvm-console-types-scalar",
  "snarkvm-console-types-field"
]
string = [
  "snarkvm-console-types-string",
  "snarkvm-console-types-field",
  "snarkvm-console-types-integers"
]
