[package]
name = "snarkvm-circuit-types-address"
version = "0.13.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Address circuit for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-types-address"
path = "../../../console/types/address"
version = "=0.13.0"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "=0.13.0"

[dependencies.snarkvm-circuit-types-boolean]
path = "../boolean"
version = "=0.13.0"

[dependencies.snarkvm-circuit-types-field]
path = "../field"
version = "=0.13.0"

[dependencies.snarkvm-circuit-types-group]
path = "../group"
version = "=0.13.0"

[dependencies.snarkvm-circuit-types-scalar]
path = "../scalar"
version = "=0.13.0"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
