[package]
name = "snarkvm-parameters"
version = "0.3.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Parameters for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.3.1"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.3.1"
default-features = false

[dependencies.curl]
version = "0.4.37"
optional = true

[dependencies.hex]
version = "0.4.3"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.snarkvm-curves]
path = "../curves"
default-features = false

[dev-dependencies.snarkvm-dpc]
path = "../dpc"
default-features = false

[dev-dependencies.snarkvm-marlin]
path = "../marlin"
default-features = false

[dev-dependencies.snarkvm-polycommit]
path = "../polycommit"
default-features = false

[dev-dependencies.snarkvm-posw]
path = "../posw"
default-features = false

[dev-dependencies.blake2]
version = "0.9"
default-features = false

[dev-dependencies.curl]
version = "0.4.34"

[dev-dependencies.hex]
version = "0.4.3"

[dev-dependencies.rand]
version = "0.8"

[features]
default = [ "remote", "snarkvm-algorithms/default" ]
remote = [ "curl" ]
