[package]
name = "snarkvm-console-types-scalar"
version = "0.16.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Type operations for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.snarkvm-console-network-environment]
path = "../../network/environment"
version = "=0.16.1"

[dependencies.snarkvm-console-types-boolean]
path = "../boolean"
version = "=0.16.1"

[dependencies.snarkvm-console-types-field]
path = "../field"
version = "=0.16.1"

[dependencies.zeroize]
version = "1"
features = [ "derive" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]
