[package]
name = "snarkvm-ledger-committee"
version = "0.16.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A committee for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
serial = [ "console/serial" ]
wasm = [ "console/wasm" ]
prop-tests = [ "rand", "rand_chacha", "test-strategy", "proptest", "anyhow" ]
test-helpers = [ "prop-tests", "rand_distr" ]

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.16.1"

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dependencies.anyhow]
version = "1.0.73"
optional = true

[dependencies.proptest]
version = "1.0.0"
optional = true

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.rand_chacha]
version = "0.3"
optional = true

[dependencies.rand_distr]
version = "0.4"
optional = true

[dependencies.test-strategy]
version = "0.3.1"
optional = true

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.parking_lot]
version = "0.12"

[dev-dependencies.rand_distr]
version = "0.4"

[dev-dependencies.rayon]
version = "1"

[dev-dependencies.snarkvm-ledger-committee]
path = "."
features = [ "prop-tests" ]
