[package]
name = "snarkvm-circuit-types-field"
version = "0.13.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Field circuit for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-types-field"
path = "../../../console/types/field"
version = "=0.13.0"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "=0.13.0"

[dependencies.snarkvm-circuit-types-boolean]
path = "../boolean"
version = "=0.13.0"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
