[package]
name = "snarkvm-circuit-program"
version = "0.14.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program circuit library for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-program"
path = "../../console/program"
version = "=0.14.0"
optional = true

[dependencies.snarkvm-circuit-account]
path = "../account"
version = "=0.14.0"

[dependencies.snarkvm-circuit-collections]
path = "../collections"
version = "=0.14.0"

[dependencies.snarkvm-circuit-network]
path = "../network"
version = "=0.14.0"

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "=0.14.0"

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "=0.14.0"

[dev-dependencies.console]
package = "snarkvm-console-program"
path = "../../console/program"
features = [ "test" ]

[dev-dependencies.snarkvm-console-account]
path = "../../console/account"

[dev-dependencies.anyhow]
version = "1.0.71"

[dev-dependencies.rand]
version = "0.8"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
