[package]
name = "snarkvm-circuit-types-boolean"
version = "0.13.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Boolean circuit for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[[bench]]
name = "and"
path = "benches/and.rs"
harness = false

[dependencies.console]
package = "snarkvm-console-types-boolean"
path = "../../../console/types/boolean"
version = "=0.13.0"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "=0.13.0"

[dev-dependencies.criterion]
version = "0.5"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
