[package]
name = "snarkvm-circuit-types-scalar"
version = "0.14.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Scalar circuit for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-types-scalar"
path = "../../../console/types/scalar"
version = "=0.14.0"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "=0.14.0"

[dependencies.snarkvm-circuit-types-boolean]
path = "../boolean"
version = "=0.14.0"

[dependencies.snarkvm-circuit-types-field]
path = "../field"
version = "=0.14.0"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
