[package]
name = "snarkvm-circuit-environment-witness"
version = "0.11.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A procedural macro to construct a witness in an environment"
license = "GPL-3.0"
edition = "2018"

[lib]
proc-macro = true
