[package]
name = "snarkvm-circuit-algorithms"
version = "0.16.19"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Algorithm circuit library for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-algorithms"
path = "../../console/algorithms"
version = "=0.16.19"
optional = true

[dependencies.snarkvm-console-types-field]
path = "../../console/types/field"
version = "0.16.6"

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "=0.16.19"

[dependencies.snarkvm-fields]
path = "../../fields"
version = "=0.16.19"
default-features = false

[dev-dependencies.anyhow]
version = "1.0.73"

[dev-dependencies.snarkvm-curves]
path = "../../curves"
default-features = false

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"
default-features = false

[dev-dependencies.serde_json]
version = "1.0"

[features]
default = [ "enable_console" ]
enable_console = [ "console" ]
